# Generated by Django 4.2.11 on 2024-04-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_document_file_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="img/%y")),
            ],
        ),
        migrations.AlterField(
            model_name="document",
            name="file_field",
            field=models.FileField(blank=True, upload_to="documents"),
        ),
    ]
